### ISSUE TITLE
Objetivos e macro-tópicos

### ISSUE THREAD

**Issue by netojoaobatista** [php-brasil/software-legado#1]
Antes de definir os tópicos de cada hangout, precisamos definir os objetivos e macro-tópicos que devemos abordar para alcançar esses objetivos.
1. O que queremos com essa série de hangouts?
2. Quem é o público alvo?
3. Qual a duração de cada hangout?

**Comment by iannsp** [comment]
objetivo da série sobre "software legado"
Dismistificar o software legado, apresentando tecnicas que ajudem o desenvolvedor a superar as dificuldades de ver, ler, analisar, compreender, manter e melhorar softwares que não tenham sido escritos
a) por ele
b) na sua década
c) com técnicas desconhecidas
d) com deficits técnicos
e) ongoing, sendo utilizados por usuarios e sem possibilidade de ações disruptivas.

**Comment by jackmakiyama** [comment]
@iannsp :+1:

**Comment by lcobucci** [comment]
O nosso público-alvo direto são desenvolvedores de softwares, mas acho que é relevante colocar os donos de empresa, líderes de equipe, gerentes, etc como indiretos.

Muito desse "misticismo" do software legado vem das pessoas que estão coordenando o gerenciamento de softwares, com frases do tipo "não toca nisso, só o Bátima pode alterar esse arquivo".

**Comment by jackmakiyama** [comment]
Boa, @lcobucci .

**Comment by netojoaobatista** [comment]
Acho que tantos as considerações do @iannsp quanto do @lcobucci são válidas. Acho, inclusive, que ambas devem constar no README.md do repositório.
