### ISSUE TITLE
Tema para o segundo Hangout

### ISSUE THREAD

**Issue by iannsp** [php-brasil/software-legado#10]
> Definir o que caberá no segundo hangout

[Decidido](https://github.com/php-brasil/software-legado/issues/10#issuecomment-70958451).

**Comment by iannsp** [comment]
Acho natural que o segundo hangout tenha como tema o "como olhar para um código legado".
Você acaba de chegar na empresa ou entrar em um projeto open source, e te apresentam um software, aquele com o qual voce vai trabalhar/se divertir.
Com que olhos você tem que enxergar as caracteristcas desse software?
Entender do contexto em que foi produzido, época, recursos disponíveis, prazo, algo próximo a uma **arqueologia de software**.

**Comment by iannsp** [comment]
http://en.wikipedia.org/wiki/Software_archaeology

**Comment by netojoaobatista** [comment]
Gosto desse tema para continuação.

**Comment by augustohp** [comment]
Conversamos hoje no [Appear.in](https://appear.in): @netojoaobatista, @iannsp, @alganet, @augustohp @jackmakiyama.

Depois de descobrir que o @iannsp não sabia que o [Jenga](http://www.jenga.com/) era um jogo e muito discutir, concordamos no seguinte:

## Iremos responder perguntas

Aqui, neste repositório mesmo, perguntas podem ser feitas e discutidas. Vamos escolher uma pro próximo Hangout e discutir somente ela.

Outras perguntas, se o tema - da pergunta - deve ser extendido, podem surgir aqui e poderão ser escolhidas também.

Vamos procurar responder às perguntas aqui com algumas referências sempre que possível, considerando sempre o _approach_ dos Hangouts como a metodologia de:
- Aula (só o nome, pq a parada não é de fato uma aula): Hangouts.
- Lição de casa: interação neste repositório.

## A pergunta do próximo Hangout

> [Quando descartar um software legado?](https://github.com/php-brasil/software-legado/issues/6)

Ela já tem algumas respostas, qualquer iteração nela ainda é extremamente válida e estimulada. Assim podemos ganhar tempo no Hangout e ter uma discussão mais rica em cima dela.

Vale direcionar algumas respostas no Hangout pra falta de códigos concretos de código legado. É bacana discutir, mas é muito mais bacana discutir em cima de um cenário real e acessível pra todo mundo.
Cobrar da galera um código não é muito amigável, mas talvez existam oportunidades de direcionar a discussão em cima da falta de exemplos concretos (e como compartilhá-los, talvez de forma anônima).

## Quando será o Hangout?

Criei [um questionário](http://doodle.com/sfrwuiu4shet93yy) sobre qual o melhor dia da semana pra cada um. :wink:
