### ISSUE TITLE
Há um momento de refazer tudo?

### ISSUE THREAD

**Issue by leocavalcante** [php-brasil/software-legado#13]
Não me odeie @iannsp, já pensei em refazer tudo algumas vezes, vou mudar essa forma de pensar, mas é justamente nessa linha minha dúvida. O @netojoaobatista disse que o cara que não pensa no refactoring esta armando uma bomba e que uma hora ela vai explodir. Se você é o infeliz de pegar essa bomba já explodida, é um momento de pensar em refazer tudo ou mesmo assim não devemos pensar assim de forma alguma?

Eu entendi por bomba explodida um código tão engessado e rígido que o custo da integração de novas features é maior que o valor que a feature agrega. É uma boa avaliação ou a bomba explodida é um caso pior?

Resumindo: mesmo nas piores situações, nas mais diversas complexidades, independente do quão rígido o código chegou, refactoring será mais produtivo do que simplesmente jogar tudo fora e começar de novo?

**Comment by leocavalcante** [comment]
Desculpa gente, eu não tinha visto as fechadas se a #6 é justamente sobre isso perdão e podem fechar.

**Comment by iannsp** [comment]
@leocavalcante relax man, o que eu sinto com relação a figura do "temos que reescrever tudo" é mais receio/medo do que ódio ;)

Sim, tratamos desse assunto na issue #6 mas veja, acho que cabe um adendo aqui. 

É muito dificil dizer que um códiog não tem salvação. para que isso seja verdade o código precisaria não ter nem um esqueleto que suportasse o peso do refactoring. Explico: Imagina uma aplicação web onde html+css+php+sql+javascript estão juntos, essa aplicação talvez não tenha salvação... mas se os conceitos estão minimamente separados e existe a possibilidade de isolar ainda mais cada um deles, então pode ser possivel o refactoring.

Algumas pessoas vão diretamente para o **jogar tudo fora e começar novamente** e eis aqui alguns itens que elas perdem:
- Ao trabalhar sobre um código antigo você pode aprender as regras de negócio(MESMO QUE O CODIGO SEJA RUIM)
- Ao trabalhar sobre codigo antigo voce pode aprender com os erros de outras pessoas
- Ao trabalhar com o código antigo você tem a chance de concluir o que é importante ou não em uma aplicação
- Ao trabalhar com um código antigo você vai ser obrigado a conhecer as pessoas, as técnicas e as de negócio.
- Ao trabalhar com código antigo você tem a chance de manter o produto atual no ar e evitar constrangimentos para a empresa.

tem muito mais de onde esses motivos sairam, mas acho que eles já são bem interessantes.

**Comment by leocavalcante** [comment]
Valeu @iannsp :)
