### ISSUE TITLE
Duração de cada hangout

### ISSUE THREAD

**Issue by netojoaobatista** [php-brasil/software-legado#3]
Temos percebido que quanto mais longo o hangout, menor o número de pessoas assistindo-o. A duração do hangout está diretamente relacionada ao alcance do hangout.

A sugestão é para que cada hangout **não ultrapasse** os 30 minutos de duração.

**Comment by lcobucci** [comment]
Concordo plenamente, um exemplo que isso dá certo é a serie `Is TDD dead?`.

**Comment by netojoaobatista** [comment]
Dei uma olhada no tempo de alguns vídeos e o número de views. Acho que a relação duração/número de views não procede.

![views](http://oi59.tinypic.com/5khzxd.jpg)

**Comment by lcobucci** [comment]
Eu acho que a coisa mais interessante em vídeos curtos é a objetividade.
Quando deixamos algo muito extenso, a tendência de perdermos ela completamente é grandissíma.

**Comment by luiscoms** [comment]
Acredito que é mais vantajoso dividir o assunto em mais videos do que ter um vídeo longo de mais de 1h.

**Comment by netojoaobatista** [comment]
Hangout definido para 50 minutos e evento criado.
