### ISSUE TITLE
Participantes de cada hangout

### ISSUE THREAD

**Issue by netojoaobatista** [php-brasil/software-legado#4]
Essa questão está diretamente relacionada com a issue #3. Se tivermos 10 participantes na sala e todos falarem sobre o tema, num hangout de duração de 30 minutos teremos 3 minutos máximos por participante.

Precisamos definir se teremos 10 participantes por hangout e se todos os 10 falarão sobre o tema proposto naquele hangout.

**Comment by drgomesp** [comment]
Algumas considerações:
- Acho que podemos extender o tempo dos hangouts para 1h30m. Acredito que a grande maioria das pessoas que assiste aos hangouts, assiste num clima de relaxamento, sem necessariamente ter pressa para absorver o conteúdo. Assim, podemos ter mais liberdade para discorrer sobre os assuntos e também nos divertimos mais.
- Com relação aos participantes, acho que 10 pessoas é muito. Eu acho que 6 seria o ideal.

**Comment by MayogaX** [comment]
Acho que 5 ou 6 é o ideal, podemos ir revezando a participação.
E acho que 1h30 é muito longo, nem todo mundo assiste algo assim.
Podemos deixar entre 30 minutos a 1 hora

**Comment by kinncj** [comment]
Um hangout de 30minutos, acredito que 4 participantes falantes seriam mais que ideal... muitos tem um brainstorm fantástico, e limitar o quanto essa pessoa pode expôr é realmente complicado.
Como citado na issue #3 , o `Is TDD dead?` é um exemplo perfeito, aonde o número de participantes (3) fez com que fosse possível um curto período de tempo para cada episódio da série.

**Comment by kinncj** [comment]
A mesma reflexão vale para uma palestra de 45minutos com mais de 2 speakers... fica realmente complicado limitar a fala de cada um, afinal são os tempos de cada fala que dão clareza no assunto.

**Comment by jackmakiyama** [comment]
Daria pra limitar em 3 ou 6 pessoas e tentar não passar do tempo, mas também não cortar o desenrolar da conversa.

**Comment by lcobucci** [comment]
Concordo com o @kinncj, acho que 4 é um número ótimo.

**Comment by jackmakiyama** [comment]
Quanto menor o numero de pessoas menos se perde o foco.

**Comment by netojoaobatista** [comment]
Defini o hangout para **50** minutos.

Independentemente do tempo do hangout, pessoalmente, gosto de volume na sala. Acho que seria legal ter os 10 participantes, mesmo que alguém tenha a participação limitada.

**Comment by jackmakiyama** [comment]
Pessoal, parabéns pelo trampo feito até aqui, gostei demais da pauta desse primeiro hangout e acho que é um ótimo início.

Já fechou os participantes?
Acho que poderia ser adcionado os nomes junto no planejamento.
