### ISSUE TITLE
Software legado em agências e Software Houses

### ISSUE THREAD

**Issue by andrebian** [php-brasil/software-legado#7]
Segundo a definição apresentada pelo @netojoaobatista no Hangout, um software legado é aquele que não é mais o principal produto de uma empresa. Levando isto em consideração as agências de desenvolvimento e Software Houses vivenciam frenéticamente o software legado. Neste cenário dificilmente existe somente 1 software sendo desenvolvido ao mesmo tempo, é correto afirmar que agências e Software Houses vivem de software legado?

**Comment by netojoaobatista** [comment]
Veja, @andrebian, quando eu disse sobre o principal, eu disse sobre o software produto. Vou tentar descrever melhor o cenário:

A fábrica de software X vende um produto software para a empresa Y. A empresa Y tem _n_ clientes que utilizam esse produto. Esse produto é o principal da empresa Y. Do ponto de vista da fábrica de software, ela tem uma carteira de produtos e todos são principais, pois cada empresa que se beneficia de seu produto, está se beneficiando de um principal.

Passa a ser legado para a fábrica de software X quando a empresa Y deixa de utilizar aquele produto e começa a utilizar um novo software. Quando a empresa Y **deixa de usar o software X** e durante todo o tempo que a fábrica de software tiver que manter o software X, essa fábrica de software estará mantendo o legado.

Então, respondendo diretamente sua pergunta: Não, não é correto definir que agências e software houses vivem de software legado.

**Comment by andrebian** [comment]
Certo, ficou clara a explicação. Obrigado.

**Comment by bscherer** [comment]
@netojoaobatista, diante de sua explicação logo acima. Seria correto entender que um software que ainda possui clientes não é um software legado?

**Comment by jackmakiyama** [comment]
@bscherer se esse software for o principal produto ele não é um legado.
Como citado o Windows 7 tem muitos clientes e ele é um legado.

**Comment by oliveiraev** [comment]
> @netojoaobatista, diante de sua explicação logo acima. Seria correto entender que um software que ainda possui clientes não é um software legado?

Se você está investindo dinheiro pra manter um software que não possui clientes, ele não é legado, é descartável.

Então, não. Não é porque um software possui clientes que não é legado.
