### ISSUE TITLE
Definir data do segundo hangout

### ISSUE THREAD

**Issue by iannsp** [php-brasil/software-legado#9]
Precisamos definir com uma antecedencia de 1 semana a data do 2o hangout.

**Comment by iannsp** [comment]
minha sugestão é que os hangouts passem a ser realizados em um dia da semana fixo, preferencialmente terça-feira.
Segunda-feira a pessoa chega no trabalho e se planeja para a semana.
terça-feira é uma janela na qual ela esta se preparando/ mergulhando nos trabalho. Da quarta-feira em diante ela ja esta envolvida e começa a ver dead-lines e etc. Levando em consideração que a maioria das empresas dão lock em deploys a partir de quinta-feira a noite, _quinta-feira é um dia quente_ quarta-feira é um dia de trampo pesado, terça-feira é a janela mais saudável para um bom aproveitamento de um hangout.

**Comment by netojoaobatista** [comment]
Eu concordo com a ideia do dia fixo. Os hangouts historicamente sempre foram feitos nas terças-feiras às 22h. O hangout anterior foi uma tentativa de conciliar o horário do @drgomesp, que está em um timezone diferente.

Mas pode ser que você tenha razão quanto ao planejamento da semana. Tivemos uma audiência ao vivo muito baixa. Principalmente se compararmos com os hangouts anteriores. Talvez seja justamente por causa do fim da semana ser _quente_.

Outra coisa que precisamos verificar é a data dos eventos do PHPSP para não haver colisão de horário.

**Comment by drgomesp** [comment]
Eu não quero ser a razão para os hangouts não estarem tendo o máximo de espectadores possível. No hangout passado, por ter sido realizado na sexta-feira em vez da quinta-feira, acabei não conseguindo participar.

Se os próximos acontecerem nas quintas-feiras, vou participar. Porém, se a maioria achar que a melhor data é a terça-feira, vou com a maioria.

**Comment by lcobucci** [comment]
Acho terça feira bem melhor. Sugiro dia 27/01.
Seria legal definirmos também uma frequência, assim só abriríamos uma issue com esta pergunta em exceções, que tal semana sim e outra não?

**Comment by lcobucci** [comment]
Agora que ouvi no final do hangout "até semana que vem"... deixamos semanal mesmo??

A ideia de ter uma semana em "branco" seria pra planejar e divulgar melhor, se vcs acharem necessário. Apenas twitter e FB não rende muito, seria legal encontrarmos outros canais (mas isso é outra discussão :smile:).

**Comment by lcobucci** [comment]
O último hangout ficou bacana, mas tivemos vários pontos que ficaram soltos e não houve uma conclusão do assunto (até pq não há 100% de concordância). Acho que seria extremamente relevante termos um "Prá nós, software legado é: ..." no final do vídeo.

Esses pontos poderiam ser alinhados e resolvidos se a gente tivesse feito um planejamento melhor.

Indo um pouco além da minha sugestão, podemos fazer um hangout (fechado) exclusivo para o planejamento do próximo capítulo da novela. Assim, definimos nossas conclusões para cada vídeo.

Seria muito bom também se estivéssemos um vídeo a frente no planejamento, para dizer com certeza durante a apresentação qual será o assunto do próximo. Para isso precisaríamos planejar o vídeo 2 e o 3 nesta semana.

**Comment by iannsp** [comment]
@lcobucci , sugestão mais que aprovada(na minha opnião).
Hangouts publicos serem quinzenais, intercalados por um hangout privado para discussão do conteúdo e planejamento de abordagem(como fizemos ano passado).
Sobre estarmos a frente, bem, pra mim isso é mais que lógico, é quase tão claro quanto saber que açucar+limão+pinga +gelo é bom bagarai :)

**Comment by netojoaobatista** [comment]
Então podemos fazer um hangout fechado essa semana para planejar o hangout público da semana que vem.

Mas não acho que precisemos ter 100% de concordância. De fato, acho que o melhor do hangout é justamente os pontos de vista diferentes. Se precisasse de 100% de concordância, bastaria fazer o hangout com uma pessoa só.

**Comment by iannsp** [comment]
@netojoaobatista precisamos avançar dando segurança aos que ouvem o hangout, no sentido de que a discussão é o mais importante e sempre será, mas precisamos apresentar um conceito final de cada hangout, mesmo que imcompleto(como no primeiro sobre a definição de software legado) mas que seja mais próximo a algo "declaravel". Isso pq é isso que o ouvinte espera saca, uma ideia da qual ele conhece a construção, mas uma ideia/conceito sobre o qual ele pode elaborar

**Comment by netojoaobatista** [comment]
Eu entendo o ponto, @iannsp.

A grande questão é que dificilmente conseguiríamos fazer isso no primeiro hangout. A discussão sobre "o que é" iniciou na issue #2, ficou sem conclusão, foi para o hangout e permaneceu sem conclusão. Não foi falta de um hangout de preparação. Foi simplesmente por, apesar de concordarmos com alguns pontos, discordarmos de outros. Acho que isso é extremamente saudável pois força o espectador a pesquisar e buscar suas próprias conclusões. 

Enfim, pessoalmente, não acho que precisamos, necessariamente, ter algo declarável. Se conseguirmos fazer com que as pessoas sintam a necessidade de pesquisar e buscar informações sobre o tema, teremos sido extremamente bem sucedidos.

De qualquer forma, eu gosto da ideia de um hangout privado para, pelo menos, organizarmos as ideias. Isso é bom pois permite que o conteúdo seja passado de forma otimizada, evitando perder tempo com rodeios.

**Comment by iannsp** [comment]
de fato :+1: 
pessoal, quem pode participar de um hangout privado essa semana, de preferencia amanhã ou quinta-feira, durante a noite, para discutirmos o proximo hangout público?

**Comment by lcobucci** [comment]
Eu havia esquecido o quão literal o @netojoaobatista era (faz tempo que não nos falamos né meu ahhahah).

A questão principal é tentarmos buscar uma definição comum, aquilo que mais concordamos (sim, não precisa ser 100%).

**Comment by alganet** [comment]
Eu posso!

**Comment by lcobucci** [comment]
Eu posso quinta a noite

**Comment by iannsp** [comment]
@drgomesp, @henriquemoody , @augustohp ?

**Comment by netojoaobatista** [comment]
Amanhã tenho aula. Para ser amanhã, precisa ser depois das 22h.

**Comment by augustohp** [comment]
Durando uma hora, acho tranquilo nos reunirmos 22h30 e começar as 23h.

Amanhã pra mim rola. Só quinta e sexta complicam bastante.

**Comment by henriquemoody** [comment]
Pra mim, se for amanhã tem que ser depois das 22h30 também.
Quinta-feira se for depois das 20h acho que também dá.

**Comment by iannsp** [comment]
fechado então amanha, dia 21-01-2015, das 22:30 até as 23:30!
objetivo: discutir a pauta do segundo hangout de Software Legado.
vamos nessa!

**Comment by augustohp** [comment]
Caras, na #10 eu criei [um questionário](http://doodle.com/sfrwuiu4shet93yy) de qual o melhor dia da semana. Acho que fica melhor pra visualizar do que na discussão.

Tendo o melhor dia, podemos fazer outro com as opções de horário.

**Comment by jackmakiyama** [comment]
:+1: 
Com esse questionário fica fácil saber o melhor dia da semana a ser realizado para todos.

**Comment by drgomesp** [comment]
Só não entendi se o doodle é pra decidir a data do hangout ou da reunião prévia ao hangout... Alguém?

**Comment by iannsp** [comment]
definir o dia para fazermos o hangout.

**Comment by augustohp** [comment]
[Doodle pra vermos o melhor horário](http://doodle.com/9r4wuuv28qp2t4wn).
